apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cdtzm968g-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.xjiang0903a.eadb.p3.openshiftapps.com/rhtap/rhtap-qe:399a181b3de185af2d54fc7cbc76faeee40253ec@sha256:2385a00459b22d701070a8f875d9e6ff0e1e1ba0efbe8bcab376675ceaad7dde
          name: container-image
